#!/bin/bash

echo "🚀 GitHub Setup Commands"
echo "========================="
echo ""
echo "📝 Step 1: Initialize Git Repository"
echo "--------------------------------------"
echo "cd '/home/dipak/Downloads/2/TimePass Project/chori ka maal'"
echo "git init"
echo ""
echo "📝 Step 2: Add All Files"
echo "--------------------------------------"
echo "git add ."
echo ""
echo "📝 Step 3: Create Initial Commit"
echo "--------------------------------------"
echo "git commit -m 'Initial commit: YouTube Video Downloader with dark theme UI'"
echo ""
echo "📝 Step 4: Create GitHub Repository"
echo "--------------------------------------"
echo "Go to: https://github.com/new"
echo "Repository name: youtube-video-downloader"
echo "Description: Modern YouTube video downloader with dark theme UI"
echo "Public/Private: Choose your preference"
echo "DO NOT initialize with README, .gitignore, or license"
echo ""
echo "📝 Step 5: Add Remote & Push"
echo "--------------------------------------"
echo "git branch -M main"
echo "git remote add origin https://github.com/YOUR_USERNAME/youtube-video-downloader.git"
echo "git push -u origin main"
echo ""
echo "✅ Done! Your project will be on GitHub"
echo ""
echo "🔄 Future Updates:"
echo "--------------------------------------"
echo "git add ."
echo "git commit -m 'Your commit message'"
echo "git push"
echo ""
